version: 2
workflows:
  version: 2
  build_test:
    jobs:
      - build
      - test:
          requires:
            - build
jobs:
  build:
    docker:
      - image: circleci/golang:1.11.1
    working_directory: /go/src/github.com/Static-Void-Academy/circleci-hello
    steps:
      - checkout # Checks out the source code
      - run: go get -d ./...
      - run:
          name: Build the executable
          command: |
            echo "Other important command here as example"
            go build
      - persist_to_workspace:
          root: . # Persist current working directory
          paths: ./* # Glob. Will persist everything in folder
      - store_artifacts:
          path: ./circleci-hello # executable
test:
    docker:
      - image: circleci/golang:1.11.1
    working_directory: /go/src/github.com/Static-Void-Academy/circleci-hello
    steps:
      - attach_workspace:
          at: .
      - checkout # Checks out the source code
      - run: go get -d ./...
      - run: go test
