version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11.1
    working_directory: /go/src/github.com/Static-Void-Academy/circleci-hello
    steps:
      - checkout # Checks out the source code
      - run: echo "Hello World!"
      - run: go get -d ./...
      - run:
          name: Build the executable
          command: |
            echo "Other important command here as example"
            go build
      - store_artifacts:
          path: ./circleci-hello # executable